# Generated by Django 5.0.7 on 2024-07-27 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_customuser_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('زن', 'زن'), ('مرد', 'مرد')], max_length=10),
        ),
    ]
