# Generated by Django 5.0.7 on 2024-08-19 13:36

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_customuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='users/covers/', validators=[core.validators.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='users/photos/', validators=[core.validators.validate_image_size]),
        ),
    ]
