# Generated by Django 5.0.7 on 2024-10-08 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_customuser_cover_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
