# Generated by Django 5.0.7 on 2024-10-14 09:19

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_customuser_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cover_photo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='users/covers/', validators=[core.validators.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_photo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='users/photos/', validators=[core.validators.validate_image_size]),
        ),
    ]
