# Generated by Django 5.0.7 on 2024-07-28 14:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('birth_city', models.CharField(max_length=255)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='actors/photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.UUIDField()),
                ('name', models.CharField(max_length=255)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='cast/photos/')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cast', to='media.actor')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.UUIDField()),
                ('detail', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
                ('is_spoiler', models.BooleanField(default=False)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_comments', to='media.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('duration', models.IntegerField()),
                ('imdb_rate', models.DecimalField(decimal_places=1, max_digits=2)),
                ('users_rate', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('description', models.TextField()),
                ('release_date', models.DateField()),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='movies/photos/')),
                ('genres', models.ManyToManyField(to='media.genre')),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('season_count', models.IntegerField(default=1)),
                ('imdb_rate', models.DecimalField(decimal_places=1, max_digits=2)),
                ('users_rate', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('release_year', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('release_time', models.TimeField()),
                ('release_day', models.CharField(max_length=50)),
                ('users_added_count', models.IntegerField(default=0)),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='shows/photos/')),
                ('genres', models.ManyToManyField(to='media.genre')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('season', models.IntegerField()),
                ('imdb_rate', models.DecimalField(decimal_places=1, max_digits=2)),
                ('users_rate', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('episode_number', models.IntegerField()),
                ('release_date', models.DateField()),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='None/<django.db.models.fields.IntegerField>/episodes/photos/')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='media.show')),
            ],
        ),
        migrations.CreateModel(
            name='UserEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_rate', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('watch_date', models.DateTimeField(auto_now_add=True)),
                ('emoji', models.CharField(blank=True, max_length=50, null=True)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_episodes', to='media.episode')),
                ('favorite_cast', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favorite_episode_cast', to='media.cast')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_episodes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched', models.BooleanField(default=False)),
                ('user_rate', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('emoji', models.CharField(blank=True, max_length=50, null=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('favorite_cast', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favorite_movie_cast', to='media.cast')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_movies', to='media.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_movies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('در حال تماشا', 'در حال تماشا'), ('متوقف شده', 'متوقف شده'), ('برای بعد', 'برای بعد')], default='در حال تماشا', max_length=50)),
                ('is_favorite', models.BooleanField(default=False)),
                ('users_rate', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_shows', to='media.show')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_shows', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
