# Generated by Django 5.0.7 on 2024-10-14 09:19

import media.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='profile_photo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='actors/photos/'),
        ),
        migrations.AlterField(
            model_name='cast',
            name='photo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='cast/photos/'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='cover_photo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=media.models.episode_cover_upload_to),
        ),
        migrations.AlterField(
            model_name='movie',
            name='cover_photo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='movies/photos/'),
        ),
    ]
