# Generated by Django 5.0.7 on 2024-07-28 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_remove_usershow_users_rate_usershow_user_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='rate_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
