# Generated by Django 5.0.7 on 2024-07-30 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_movie_rate_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_proved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movie',
            name='added_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='show',
            name='users_rate_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='show',
            name='users_added_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
