# Generated by Django 5.0.7 on 2024-08-03 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0006_remove_comment_likes_comment_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
