# Generated by Django 5.0.7 on 2024-08-13 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0007_alter_comment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermovie',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True, default='2024-05-02'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='media.comment'),
        ),
    ]
