# Generated by Django 5.0.7 on 2024-08-13 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0008_usermovie_added_date_alter_comment_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='added_count',
            new_name='users_added_count',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='rate_count',
            new_name='users_rate_count',
        ),
    ]
