# Generated by Django 5.0.7 on 2024-08-14 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0010_usermovie_watched_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='end_year',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
