# Generated by Django 5.0.7 on 2024-08-15 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0011_show_end_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usershow',
            name='status',
            field=models.CharField(choices=[('در حال تماشا', 'در حال تماشا'), ('متوقف شده', 'متوقف شده'), ('برای بعد', 'برای بعد')], default=None, max_length=50),
        ),
    ]
