# Generated by Django 5.0.7 on 2024-08-15 11:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0012_alter_usershow_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='follow_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
