# Generated by Django 5.0.7 on 2024-08-15 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0013_follow_follow_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
