# Generated by Django 5.0.7 on 2024-08-19 13:36

import media.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0014_actor_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to=media.models.episode_cover_upload_to),
        ),
        migrations.AlterField(
            model_name='usershow',
            name='status',
            field=models.CharField(choices=[('در حال تماشا', 'در حال تماشا'), ('متوقف شده', 'متوقف شده'), ('برای بعد', 'برای بعد')], default=None, max_length=50, null=True),
        ),
    ]
