# Generated by Django 5.0.7 on 2024-08-19 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0015_alter_episode_cover_photo_alter_usershow_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='is_released',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='is_released',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='show',
            name='is_released',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
