# Generated by Django 5.0.7 on 2024-08-20 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0016_episode_is_released_movie_is_released_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermovie',
            name='watched_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
