# Generated by Django 5.0.7 on 2024-08-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0017_alter_usermovie_watched_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='network',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
