# Generated by Django 5.0.7 on 2024-08-24 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0018_show_network'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
