# Generated by Django 5.0.7 on 2024-08-25 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0019_show_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usershow',
            name='status',
            field=models.CharField(choices=[(None, None), ('در حال تماشا', 'در حال تماشا'), ('متوقف شده', 'متوقف شده'), ('برای بعد', 'برای بعد')], default=None, max_length=50, null=True),
        ),
    ]
