# Generated by Django 5.0.7 on 2024-09-05 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0020_alter_usershow_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='imdb_url',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
