# Generated by Django 5.0.7 on 2024-09-06 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0021_show_imdb_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='release_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
