# Generated by Django 5.0.7 on 2024-09-06 12:24

import media.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0022_alter_show_duration_alter_show_release_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to=media.models.show_cover_upload_to),
        ),
        migrations.AlterField(
            model_name='show',
            name='season_count',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
