# Generated by Django 5.0.7 on 2024-09-06 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0023_alter_show_cover_photo_alter_show_season_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='release_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
