# Generated by Django 5.0.7 on 2024-09-25 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0024_alter_show_release_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='imdb_url',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
