# Generated by Django 5.0.7 on 2024-10-09 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0026_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='is_accepted',
            field=models.BooleanField(default=True),
        ),
    ]
