# Generated by Django 5.0.7 on 2024-10-13 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0027_follow_is_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userepisode',
            name='watch_date',
            field=models.DateTimeField(),
        ),
    ]
