# Generated by Django 5.0.7 on 2024-10-13 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0028_alter_userepisode_watch_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userepisode',
            name='watch_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
